name: "commit-master"

on:
  push:
    branches: 
    - 'master'
env: 
  ipaddr: ${ip_address}
  REGIONID: ${region_id}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out 
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    # 完成java项目打包
    - name: build maven project
      run: mvn clean -U package -Dmaven.test.skip 

    # 上传当前版本到OBS中归档，需要提前准备OBS的AK/SK,并在github项目添加ACCESSKEY和HUAWEI_SK两个SECRETACCESSKEY
    - name: Upload To Huawei OBS
      uses: huaweicloud/obs-helper@v1.0.0
      id: upload_file_to_obs
      with:
        access_key: ${{ secrets.ACCESSKEY }}
        secret_key: ${{ secrets.SECRETACCESSKEY }}
        region: ${{ env.REGIONID }}
        bucket_name: bucket-test
        operation_type: upload
        local_file_path: target/demoapp.jar
        obs_file_path: workflow/springboot-web/v1.0.0.1/

    # 安装sshpass
    - name: install sshpass
      run: sudo apt-get -y update && sudo apt-get install -y sshpass

    # 检查并安装jdk,当前demo需要安装jdk1.8,高版本可能不兼容
    - name: install sshpass
      run: sshpass -p ${{ secrets.PASSWORD }}  ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@ "yum install -y java-1.8.0-openjdk  java-1.8.0-openjdk-devel"

    # 停止服务,初次部署可以跳过
    - name: stop service
      run: |
         sshpass -p ${{ secrets.PASSWORD }}  ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ env.ipaddr }} "systemctl stop demoapp.service"

    # 备份老版本,初次部署可以跳过
    - name: backup old service
      run: |
        currentDate=`date +%Y-%m-%d-%H-%M-%S`
        sshpass -p ${{ secrets.PASSWORD }}  ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ env.ipaddr }} "mkdir -p /opt/backup/demoapp/\$currentDate/"
        sshpass -p ${{ secrets.PASSWORD }}  ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ env.ipaddr }} "mv /usr/local/demoapp.jar /opt/backup/demoapp/\$currentDate/"

    # 部署服务 部署jar包，并添加到systemctl 服务器中，方便启停
    - name: deploy springweb jar to remote server
      run: |
        sshpass -p ${{ secrets.PASSWORD }}  scp  -o StrictHostKeyChecking=no  target/demoapp.jar ${{ secrets.USERNAME }}@${{ env.ipaddr }}:/usr/local/
        sshpass -p ${{ secrets.PASSWORD }}  scp  -o StrictHostKeyChecking=no  bin/demoapp.service ${{ secrets.USERNAME }}@${{ env.ipaddr }}:/etc/systemd/system/
        sshpass -p ${{ secrets.PASSWORD }}  scp  -o StrictHostKeyChecking=no  bin/start-demoapp.sh ${{ secrets.USERNAME }}@${{ env.ipaddr }}:/usr/local/
        sshpass -p ${{ secrets.PASSWORD }}  scp  -o StrictHostKeyChecking=no  bin/stop-demoapp.sh ${{ secrets.USERNAME }}@${{ env.ipaddr }}:/usr/local/
        sshpass -p ${{ secrets.PASSWORD }}  ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ env.ipaddr }} "chmod 755 /usr/local/start-demoapp.sh && chmod 755 /usr/local/stop-demoapp.sh"
        sshpass -p ${{ secrets.PASSWORD }}  ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ env.ipaddr }} "systemctl daemon-reload"

    
    # 启动服务
    - name: start spring-web application
      run: |
        sshpass -p ${{ secrets.PASSWORD }}  ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ env.ipaddr }} "systemctl start demoapp.service"
        
 
    # 检测前端页面和后端接口是否都能正常访问
    - name: check web app status
      run: |
        sleep 30
        curl -kv http://${{ env.ipaddr }}:8080/